demo_and_tests/demo_project/urls.py
# django
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import TemplateView


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(
        r'^$',
        TemplateView.as_view(template_name='home.html'),
        name='home'
    ),
    url(
        r'^files/',
        include('db_file_storage.urls')
    ),
    url(
        r'^model_files/',
        include('model_filefields_example.urls', namespace='model_files')
    ),
    url(
        r'^form_wizard/',
        include('form_wizard_example.urls', namespace='form_wizard')
    ),
]

demo_and_tests/form_wizard_example/urls.py
# django
from django.conf.urls import url
# project
from .views import SongLyricsWizard


urlpatterns = [
    url(r'^song_lyrics/$', SongLyricsWizard.as_view(), name='song_lyrics'),
]

demo_and_tests/model_filefields_example/urls.py
# django imports
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

# project imports
from .forms import BookForm, SoundDeviceForm
from .models import Book, SoundDevice


urlpatterns = [
    url(
        r'^$',
        ListView.as_view(
            queryset=Book.objects.all(),
            template_name='model_filefields_example/book_list.html'
        ),
        name='book.list'
    ),
    url(
        r'^books/add/$',
        CreateView.as_view(
            model=Book,
            form_class=BookForm,
            template_name='model_filefields_example/book_form.html',
            success_url=reverse_lazy('model_files:book.list')
        ),
        name='book.add'
    ),
    url(
        r'^books/edit/(?P<pk>\d+)/$',
        UpdateView.as_view(
            model=Book,
            form_class=BookForm,
            template_name='model_filefields_example/book_form.html',
            success_url=reverse_lazy('model_files:book.list')
        ),
        name='book.edit'
    ),
    url(
        r'^books/delete/(?P<pk>\d+)/$',
        DeleteView.as_view(
            model=Book,
            success_url=reverse_lazy('model_files:book.list')
        ),
        name='book.delete'
    ),
    url(
        r'^sound_devices/add/$',
        CreateView.as_view(
            model=SoundDevice,
            form_class=SoundDeviceForm,
            template_name='model_filefields_example/sound_device_form.html',
            success_url=reverse_lazy('model_files:book.list')
        ),
        name='sound_device.add'
    ),
]

demo_and_tests/form_wizard_example/models.py
# django
from django.db import models


class FormWizardTempFile(models.Model):
    content = models.TextField()
    name = models.CharField(max_length=255)
    mimetype = models.CharField(max_length=50)

demo_and_tests/model_filefields_example/models.py
# django
from django.core.urlresolvers import reverse
from django.db import models
# third party
from db_file_storage.model_utils import delete_file, delete_file_if_needed


class BookIndex(models.Model):
    book_index_pk = models.AutoField(primary_key=True)
    bytes = models.TextField()
    filename = models.CharField(max_length=255)
    mimetype = models.CharField(max_length=50)


class BookPages(models.Model):
    book_pages_pk = models.AutoField(primary_key=True)
    bytes = models.TextField()
    filename = models.CharField(max_length=255)
    mimetype = models.CharField(max_length=50)


class BookCover(models.Model):
    book_cover_pk = models.AutoField(primary_key=True)
    bytes = models.TextField()
    filename = models.CharField(max_length=255)
    mimetype = models.CharField(max_length=50)


class Book(models.Model):
    book_pk = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, unique=True)
    index = models.FileField(
        upload_to='model_filefields_example.BookIndex/bytes/filename/mimetype',
        blank=True, null=True
    )
    pages = models.FileField(
        upload_to='model_filefields_example.BookPages/bytes/filename/mimetype',
        blank=True, null=True
    )
    cover = models.ImageField(
        upload_to='model_filefields_example.BookCover/bytes/filename/mimetype',
        blank=True, null=True
    )

    def get_absolute_url(self):
        return reverse('model_files:book.edit', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        delete_file_if_needed(self, 'index')
        delete_file_if_needed(self, 'pages')
        super(Book, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        super(Book, self).delete(*args, **kwargs)
        delete_file(self, 'index')
        delete_file(self, 'pages')

    def __str__(self):
        return self.name


class SoundDeviceInstructionManual(models.Model):
    bytes = models.TextField()
    filename = models.CharField(max_length=255)
    mimetype = models.CharField(max_length=50)


class SoundDevice(models.Model):
    name = models.CharField(max_length=100)
    instruction_manual = models.FileField(
        upload_to='model_filefields_example.SoundDeviceInstructionManual'
                  '/bytes/filename/mimetype',
        blank=True,
        null=True
    )

demo_and_tests/form_wizard_example/forms.py
# django
from django import forms


class SongLyricsForm1(forms.Form):
    song = forms.CharField(max_length=100)
    artist = forms.CharField(max_length=100)


class SongLyricsForm2(forms.Form):
    attachment = forms.FileField(label='Lyrics', help_text='a plain text file')


class SongLyricsForm3(forms.Form):
    sender = forms.CharField(max_length=100)

demo_and_tests/model_filefields_example/forms.py
# django
from django import forms
from django.contrib.admin.forms import forms as adminforms
# third party
from db_file_storage.form_widgets import DBClearableFileInput, \
    DBAdminClearableFileInput
# project
from .models import Book, SoundDevice


class BookForm(forms.ModelForm):
    class Meta(object):
        model = Book
        exclude = []
        widgets = {
            'index': DBClearableFileInput,
            'pages': DBClearableFileInput,
            'cover': DBClearableFileInput,
        }


class BookAdminForm(adminforms.ModelForm):
    class Meta(object):
        model = Book
        exclude = []
        widgets = {
            'index': DBAdminClearableFileInput,
            'pages': DBAdminClearableFileInput,
            'cover': DBAdminClearableFileInput,
        }


class SoundDeviceForm(forms.ModelForm):
    class Meta(object):
        model = SoundDevice
        exclude = []

demo_and_tests/form_wizard_example/views.py
# python
import sys
# django
from django.shortcuts import render
# third party
from db_file_storage.storage import FixedModelDatabaseFileStorage
from formtools.wizard.views import SessionWizardView
# project
from .forms import SongLyricsForm1, SongLyricsForm2, SongLyricsForm3


class SongLyricsWizard(SessionWizardView):
    file_storage = FixedModelDatabaseFileStorage(
        model_class_path='form_wizard_example.FormWizardTempFile',
        content_field='content',
        filename_field='name',
        mimetype_field='mimetype'
    )
    form_list = [SongLyricsForm1, SongLyricsForm2, SongLyricsForm3]
    template_name = 'form_wizard_example/form.html'

    def done(self, form_list, **kwargs):
        if sys.version_info.major == 3:  # python3
            form_list = list(form_list)
        song = form_list[0].cleaned_data['song']
        artist = form_list[0].cleaned_data['artist']
        lyrics = form_list[1].cleaned_data['attachment'].read()
        sender = form_list[2].cleaned_data['sender']

        context = {'song': song, 'artist': artist,
                   'lyrics': lyrics, 'sender': sender}
        return render(self.request, 'form_wizard_example/done.html', context)

demo_and_tests/form_wizard_example/templates/form_wizard_example/done.html
<table border="1">
    <tr>
        <th>Song</th>
        <td>{{ song }}</td>
    </tr>
    <tr>
        <th>Artist</th>
        <td>{{ artist }}</td>
    </tr>
    <tr>
        <th>Lyrics</th>
        <td>{{ lyrics|linebreaks }}</td>
    </tr>
    <tr>
        <th>Sender</th>
        <td>{{ sender }}</td>
    </tr>
</table>
<hr/>
<div align='center'>
    <a href="{% url 'home' %}">Home</a>
</div>

demo_and_tests/form_wizard_example/templates/form_wizard_example/form.html
<p>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <table>
        {{ wizard.management_form }}
        {% if wizard.form.forms %}
            {{ wizard.form.management_form }}
            {% for form in wizard.form.forms %}
                {{ form }}
            {% endfor %}
        {% else %}
            {{ wizard.form }}
        {% endif %}
    </table>

    {% if wizard.steps.prev %}
        <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}">first step</button>
        <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">prev step</button>
    {% endif %}

    <input type="submit" value="submit"/>

</form>
<hr/>
<div align='center'>
    <a href="{% url 'home' %}">Home</a>
</div>

demo_and_tests/model_filefields_example/templates/model_filefields_example/book_confirm_delete.html
<form method='post'>
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type='submit' value='Confirm' />
</form>
<hr/>
<div align='center'>
    <a href='{% url "model_files:book.list" %}'>Back to list</a>
</div>
<hr/>
<div align='center'>
    <a href="{% url 'home' %}">Home</a>
</div>

demo_and_tests/model_filefields_example/templates/model_filefields_example/book_form.html
<form method='post' {% if form.is_multipart %}enctype='multipart/form-data'{% endif %}>
    {% csrf_token %}
    {{ form.as_p }}
    <p>
        <input type='submit' />
    </p>
</form>
{% if form.instance.pk %}
    <hr/>
    <div align='center'>
        <a href='{% url "model_files:book.delete" pk=form.instance.pk %}'>Delete</a>
    </div>
{% endif %}
<hr/>
<div align='center'>
    <a href='{% url "model_files:book.list" %}'>Back to list</a>
</div>
<hr/>
<div align='center'>
    <a href="{% url 'home' %}">Home</a>
</div>

demo_and_tests/model_filefields_example/templates/model_filefields_example/book_list.html
<style>
    table {
        width: 100%;
    }
    table td {
        text-align: center;
        border-bottom: 1px solid black;
    }
</style>

<a href='{% url "model_files:book.add" %}'>Add Book</a>

<hr />

{% if object_list %}
    <table>
        {% for obj in object_list %}
            <tr>
                <td>
                    <a href='{{ obj.get_absolute_url }}'>{{ obj.pk }}</a>
                </td>
                <td>
                    <a href='{{ obj.get_absolute_url }}'>{{ obj }}</a>
                </td>
                <td>
                    {% if obj.index %}
                        <a href='{% url "db_file_storage.download_file" %}?name={{ obj.index }}'>
                            <i>Download index</i>
                        </a>
                    {% endif %}
                </td>
                <td>
                    {% if obj.pages %}
                        <a href='{% url "db_file_storage.download_file" %}?name={{ obj.pages }}'>
                            <i>Download pages</i>
                        </a>
                    {% endif %}
                </td>
                <td>
                    {% if obj.cover %}
                        <a href='{% url "db_file_storage.get_file" %}?name={{ obj.cover }}' target='_blank'>
                            <img height=64 width=64 src="{% url 'db_file_storage.get_file' %}?name={{ obj.cover }}" />
                        </a>
                        <br/>
                        <a href='{% url "db_file_storage.download_file" %}?name={{ obj.cover }}'>
                            <i>Download</i>
                        </a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <p>No items found.</p>
{% endif %}
<hr/>
<div align='center'>
    <a href="{% url 'home' %}">Home</a>
</div>

demo_and_tests/model_filefields_example/templates/model_filefields_example/sound_device_form.html
<form method='post' {% if form.is_multipart %}enctype='multipart/form-data'{% endif %}>
    {% csrf_token %}
    {{ form.as_p }}
    <p>
        <input type='submit' />
    </p>
</form>
<hr/>
<div align='center'>
    <a href="{% url 'home' %}">Home</a>
</div>

demo_and_tests/templates/home.html
<h1>django-db-file-storage Demo</h1>

<hr/>

<h2>
    <span>Model Field Example: </span>
    <a href="{% url 'model_files:book.list' %}">Books List</a>
</h2>

<hr/>

<h2>
    <span>Form Wizard Example: </span>
    <a href="{% url 'form_wizard:song_lyrics' %}">Song Lyrics</a>
</h2>